In [2]:

pip install numpy

   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
    --------------------------------------- 0.3/12.3 MB ? eta -:--:--
    --------------------------------------- 0.3/12.3 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.3 MB 932.9 kB/s eta 0:00:13
   - -------------------------------------- 0.5/12.3 MB 932.9 kB/s eta 0:00:13
   - -------------------------------------- 0.5/12.3 MB 932.9 kB/s eta 0:00:13
   -- ------------------------------------- 0.8/12.3 MB 569.3 kB/s eta 0:00:21
   -- ------------------------------------- 0.8/12.3 MB 569.3 kB/s eta 0:00:21
   -- ------------------------------------- 0.8/12.3 MB 569.3 kB/s eta 0:00:21
   --- ------------------------------------ 1.0/12.3 MB 529.9 kB/s eta 0:00:22
   --- ------------------------------------ 1.0/12.3 MB 529.9 kB/s eta 0:00:22
   --- -----------

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.


In [3]:
import numpy as np

In [4]:
numpy_array=np.array([1,2,3,4,5])

In [7]:

numpy_array

array([1, 2, 3, 4, 5])

In [8]:
type(numpy_array)

numpy.ndarray

In [14]:

td_array=np.array([[1,2,3],[4,5,6]])

In [16]:
td_array

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
threed_array=np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])

In [18]:
threed_array

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

np.array---->creating multdimentional arrays

In [ ]:
np.array([1,2,3,4,5],dtype=np.int32)#dtype etle data type (int float bool)

array([1, 2, 3, 4, 5], dtype=int32)

In [21]:
np.array([7,8,9,10,11],dtype=np.int64)

array([ 7,  8,  9, 10, 11])

In [ ]:
np.array([1,2,3,4,5],dtype=np.int32)

In [22]:
np.arange(16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [23]:
np.arange(1,16)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [24]:
np.arange(5,16)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [25]:
np.arange(2,21,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [27]:
arange_data=np.arange(1,17)

In [ ]:
arange_data.reshape(4,4)#(RXC) DEVANO EVI RITE KE DATA STORE THAI SAKE BARABAR RITE 

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [29]:
arange_data.reshape(2,8)

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16]])

In [32]:
np.arange(2,17,2).reshape(4,2)

array([[ 2,  4],
       [ 6,  8],
       [10, 12],
       [14, 16]])

In [33]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [34]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [35]:
np.zeros((4,4),dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [37]:
np.random.random((3,4))

array([[0.21336468, 0.25072988, 0.98988324, 0.0705832 ],
       [0.3369908 , 0.77560171, 0.84281676, 0.3648191 ],
       [0.34669944, 0.56661115, 0.32200772, 0.56686993]])

In [40]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.linspace(-10,10,10)#(str,end,number of element)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [57]:
arr=np.array([[1,2,3,3,2,2,2],[11,33,22,34,66,77,11]])

In [58]:
arr

array([[ 1,  2,  3,  3,  2,  2,  2],
       [11, 33, 22, 34, 66, 77, 11]])

In [59]:
arr.ndim

2

In [61]:
arr.shape

(2, 7)

In [62]:
arr.size

14

In [63]:
arr.itemsize

8

In [64]:
arr.dtype

dtype('int64')

In [65]:
arr=np.arange(1,10).reshape(3,3)

In [66]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr.astype('float64')#change datatype

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [70]:
arr=np.random.random((3,3))*100

In [74]:
arr=arr.astype("int32")

In [75]:
arr=np.round(arr)

In [76]:
arr

array([[98, 23, 36],
       [23, 91,  9],
       [87, 81, 25]], dtype=int32)

In [77]:
arr+2

array([[100,  25,  38],
       [ 25,  93,  11],
       [ 89,  83,  27]], dtype=int32)

In [78]:
arr-2

array([[96, 21, 34],
       [21, 89,  7],
       [85, 79, 23]], dtype=int32)

In [79]:
arr*2

array([[196,  46,  72],
       [ 46, 182,  18],
       [174, 162,  50]], dtype=int32)

In [80]:
arr/2

array([[49. , 11.5, 18. ],
       [11.5, 45.5,  4.5],
       [43.5, 40.5, 12.5]])

In [81]:
arr>60

array([[ True, False, False],
       [False,  True, False],
       [ True,  True, False]])

In [82]:
arr<60

array([[False,  True,  True],
       [ True, False,  True],
       [False, False,  True]])

In [83]:
arr==60

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [84]:
arr==98

array([[ True, False, False],
       [False, False, False],
       [False, False, False]])

In [85]:
arr1=np.arange(1,17).reshape(4,4)

In [86]:
arr2=np.arange(17,33).reshape(4,4)

In [87]:
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [88]:
arr2

array([[17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [89]:
arr1+arr2

array([[18, 20, 22, 24],
       [26, 28, 30, 32],
       [34, 36, 38, 40],
       [42, 44, 46, 48]])

In [90]:
arr1*arr2

array([[ 17,  36,  57,  80],
       [105, 132, 161, 192],
       [225, 260, 297, 336],
       [377, 420, 465, 512]])

In [91]:
np.max(arr1)

np.int64(16)

In [92]:
arr3=arr=np.round(np.random.random((4,4))*100).astype("int32")

In [93]:
arr3

array([[28, 51,  5, 33],
       [37, 36, 80, 79],
       [26, 50, 35, 59],
       [ 7, 94, 70, 78]], dtype=int32)

In [94]:
np.max(arr3,axis=0)

array([37, 94, 80, 79], dtype=int32)

In [95]:
np.max(arr,axis=1)

array([51, 80, 59, 94], dtype=int32)

In [98]:
np.max(arr3,axis=1)

array([51, 80, 59, 94], dtype=int32)

In [99]:
np.min(arr3,axis=0)

array([ 7, 36,  5, 33], dtype=int32)

In [100]:
np.min(arr3,axis=1)

array([ 5, 36, 26,  7], dtype=int32)

In [101]:
np.sum(arr3)

np.int64(768)

In [102]:
np.sum(arr3,axis=0)

array([ 98, 231, 190, 249])

In [103]:
np.sum(arr3,axis=1)

array([117, 232, 170, 249])

In [104]:
np.prod(arr3)

np.int64(7438514203840143360)

In [105]:
np.prod(arr3,axis=0)

array([  188552,  8629200,   980000, 11997414])

In [106]:
np.prod(arr3,axis=1)

array([ 235620, 8418240, 2684500, 3592680])