### STATISTICAL FUNCTIONS

In [2]:
import numpy as np

In [9]:
arr=np.array([[12,22,22,33],[22,33,44,55],[11,45,66,22],[11,44,66,77]])

In [10]:
np.mean(arr)

np.float64(36.5625)

In [11]:
np.mean(arr,axis=1)

array([22.25, 38.5 , 36.  , 49.5 ])

In [12]:
np.mean(arr,axis=0)

array([14.  , 36.  , 49.5 , 46.75])

In [13]:
##std() standard derivation

In [ ]:
np.std(arr)#can also use axis 

np.float64(20.423542634665516)

In [15]:
##median()

In [17]:
np.median(arr)#also use axis 

np.float64(33.0)

In [18]:
#var() variance

In [20]:
np.var(arr)#also axis

np.float64(417.12109375)

### Trignometric Function

In [21]:
np.sin(0)

np.float64(0.0)

In [22]:
np.sin(45)

np.float64(0.8509035245341184)

In [23]:
np.cos(45)

np.float64(0.5253219888177297)

In [24]:
np.tan(45)

np.float64(1.6197751905438615)

In [30]:
matrix_1=np.round(np.random.random((3,4))*100).astype('int32')
matrix_1

array([[100,  31,  74,  49],
       [ 39,   6,  25,  87],
       [ 34,   5,  53,  76]], dtype=int32)

In [32]:
matrix_2=np.round(np.random.random((4,3))*100).astype('int32')
matrix_2

array([[ 17,  98,  92],
       [ 36,   2,  96],
       [ 16,  59,  61],
       [ 12,  92, 100]], dtype=int32)

In [33]:
np.dot(matrix_1,matrix_2)

array([[ 4588, 18736, 21590],
       [ 2323, 13313, 14389],
       [ 2518, 13461, 14441]], dtype=int32)

In [34]:
np.log(10)

np.float64(2.302585092994046)

In [35]:
np.log(matrix_1)

array([[4.60517019, 3.4339872 , 4.30406509, 3.8918203 ],
       [3.66356165, 1.79175947, 3.21887582, 4.46590812],
       [3.52636052, 1.60943791, 3.97029191, 4.33073334]])

In [36]:
## exp ->e

In [37]:
np.exp(matrix_1)

array([[2.68811714e+43, 2.90488497e+13, 1.37338298e+32, 1.90734657e+21],
       [8.65934004e+16, 4.03428793e+02, 7.20048993e+10, 6.07603023e+37],
       [5.83461743e+14, 1.48413159e+02, 1.04137594e+23, 1.01480039e+33]])

In [ ]:
print(np.ceil(1.6))#nextt
print(np.floor(1.6))#privious
print(np.round(1.6))#near

2.0
1.0
2.0


In [ ]:
## Transpose->Transpose of the given matrix
##syntax np.transpose() or arr.T()
###T->(i,j)--->(j,i)

In [43]:
arr=np.arange(1,17).reshape(4,4)
np.transpose(arr)

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]])

In [44]:
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [46]:
print(arr.T)

[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]


In [47]:
#ravel()->convert array to 1D array

In [48]:
np.ravel(arr)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [49]:
#Indexing and Slicing

In [51]:
arr=np.round(np.random.random((5,5))*100).astype('int32')

In [52]:
arr

array([[26, 72, 72, 45, 52],
       [46, 99, 54, 19, 20],
       [52, 46, 52, 88, 82],
       [29, 16, 62, 68, 76],
       [54,  9, 67,  5, 56]], dtype=int32)

In [ ]:
arr[3][3]#row column
#or
arr[3,3]#row,column

np.int32(68)

In [55]:
#indexing in 3D array--->[z-axis,x axis,y axis]

In [56]:
arr=np.arange(1,9).reshape(2,2,2)

In [57]:
arr

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [58]:
arr[1][0][1]

np.int64(6)

In [59]:
arr=np.round(np.random.random((5,5))*100).astype('int32')

In [62]:
#SLICING 
#2D ARRAY :[ROW1:ROW2,COL1:COL2]

In [63]:
arr[:2]

array([[35, 62,  2, 68, 65],
       [47, 32, 41, 20, 17]], dtype=int32)

In [64]:
arr[:,2]

array([ 2, 41,  0, 38,  9], dtype=int32)

In [65]:
arr[0,:]

array([35, 62,  2, 68, 65], dtype=int32)

In [66]:
arr[2:4]

array([[67, 65,  0, 21, 38],
       [93, 55, 38, 70, 25]], dtype=int32)

In [67]:
arr[2:4,3:5]

array([[21, 38],
       [70, 25]], dtype=int32)

In [68]:
arr2=np.arange(1,9)

In [71]:
for i in arr2 :
    print(i)

1
2
3
4
5
6
7
8


In [72]:
arr3=np.arange(1,17).reshape(4,4)

In [ ]:
for i in arr3:
    print(i)

[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]
[13 14 15 16]


In [76]:
arr4=np.arange(1,28).reshape(3,3,3)

In [77]:
arr4

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [79]:
for i in arr4:
    print(i)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]
[[19 20 21]
 [22 23 24]
 [25 26 27]]


In [ ]:
#nditer()-->itration in any of nd array

In [82]:
for i in np.nditer(arr4):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27


In [ ]:
##STACKING AND SPLITTING->SIZE OF THE ARRAY SHOULD SAME
#ARRAY1+ARRAY2=STACKING(hstack((args)),vstack((args)))
#SPLITING:SPLIT THE ARRAY(hsplit(array,bhag),vsplit(array,bhag)
#horizontal->row
#vertical->column

In [84]:
a1=np.arange(1,13).reshape(3,4)
a1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [85]:
a2=np.arange(13,25).reshape(3,4)
a2

array([[13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [86]:
h_a=np.hstack((a1,a2))

In [87]:
h_a

array([[ 1,  2,  3,  4, 13, 14, 15, 16],
       [ 5,  6,  7,  8, 17, 18, 19, 20],
       [ 9, 10, 11, 12, 21, 22, 23, 24]])

In [88]:
v_a=np.vstack((a1,a2))
v_a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [90]:
h_s=np.hsplit(a1,2)
h_s

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12]])]

In [92]:
v_s=np.vsplit(v_a,2)
v_s

[array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]])]